### ISSUE TITLE
set up favicon and thumbnail image

### ISSUE THREAD

**Issue by alexrandaccio** [alexrandaccio/plurality.net#3]
The site currently has no favicon, we should add one.

![image](https://user-images.githubusercontent.com/48193894/224111990-1b1db3a1-a154-40b2-8787-41fba6f1765a.png)

The site has no thumbnail either, we should add one.

![image](https://user-images.githubusercontent.com/48193894/224112112-cbf47a71-13cd-493b-9a6d-bc4fd57792aa.png)

If you want to work on this, leave a comment below and I will assign it to you!

**Comment by Tofuswang** [comment]
![Favcon](https://github.com/alexrandaccio/plurality.net/assets/63849953/817e392b-132b-48bf-b602-e6da38ff6bf3)

**Comment by akinorioyama** [comment]
@Tofuswang Thank you for the design and update. It went live ;)
